version: '3.9'

services:
  red-enlace:
    build: ./red-enlace
    container_name: pos-integration-server
    restart: unless-stopped
    ports:
      - "5454:5454"
      - "8001:8000"
    environment:
      - NODE_ENV=production

  biometrico:
    build: ./biometrico
    container_name: biometrico-server
    restart: unless-stopped
    ports:
      - "5001:5000"